### ISSUE TITLE
Option for Enemy Courses

### ISSUE THREAD

**Issue by SafetyFlux** [HBroHei/NSMRWii#15]
Given that half the randomized levels I come across are just variations of the enemy courses (the ones you usually get when bumping into an enemy in the overworld), it would be nice if there was an option to keep those self-contained or vanilla. Additionally, it's annoying to run into full regular levels at these locations. This is already an option for Toad houses and cannon levels, so it would be nice to have this as a feature as well.

**Comment by HBroHei** [comment]
The "Map" section of the [genereator](https://hbrohei.github.io/NSMRWii/generator) is now overhauled to include additional options,  which includes skipping randomising enemy ambush with other levels.

Thanks for the suggestion!
