### ISSUE TITLE
"Do not randomise zones" option not working

### ISSUE THREAD

**Issue by Cubix382** [HBroHei/NSMRWii#18]
While playing with the newest Beta Release (v2.0.0.1), I checked the "do not randomize zones" option, but when I played the actual game, the game still randomized the areas and zones inside the levels. This led to me getting softlocked in some levels (Yes I also had the "Randomise Entrance" option unchecked).

**Comment by HBroHei** [comment]
Thanks for reporting the issue to me!

That feature is currently only committed to GitHub a week ago, but not released yet. I will either add labelling to indicate it is coming soon, or release the code along with a fix to the "softlock" problem you have mentioned by today.

If you want to try out that feature, you may download and replace "randomise_zones_.py" in the program's root folder [here](https://github.com/HBroHei/NSMRWii/blob/0bcb500f7366dcd30bffc606052a2a214bf05332/randomise_zones_.py) (Click "Download raw file")

**Comment by HBroHei** [comment]
Also, if you can, mind sending the config.json file to me so that I can vertify that the "softlock" issue is fixed once I find a fix for it?

**Comment by HBroHei** [comment]
["beta v2.0.0.2"](https://github.com/HBroHei/NSMRWii/releases/tag/beta2.0.0.2) has now been released, with support for the "Do not randomise zones" option and other features and bug fixes. Thank you for your patient!

**Comment by Cubix382** [comment]
Ok thank you, I will send you the config.json as soon as I have access to my computer.

**Comment by Cubix382** [comment]
[config.json](https://github.com/user-attachments/files/16987041/config.json)
This is the config.json file for the softlock, it happens on 5-3 where it loops between 2 different areas with no exit/flagpole.

**Comment by HBroHei** [comment]
The config file should work fine for now.
Let me know when you encounter another softlock situation.
