### ISSUE TITLE
mac "randomizer_basic.py" file is gone

### ISSUE THREAD

**Issue by victor3141** [HBroHei/NSMRWii#19]
followed the guide to get the randomizer, according to the guide there is a randomizer_basic.py to randomize it for the mac... there is no such file for some reason

**Comment by HBroHei** [comment]
"randomizer_basic.py"has been renamed to "main.py" in V1 and "main_v1.py" in V2.
The main Python script file for V2 is "randomise_zones_.py". I have already updated the names for them in [here](https://hbrohei.github.io/NSMRWii/generator/tut.html)

Mind telling me where you get the guide from? I will update the information with the latest one.

**Comment by HBroHei** [comment]
This issue will be marked as **close**.
If you have any updates, please let me know. Thank you!
