### ISSUE TITLE
Discord link is broken

### ISSUE THREAD

**Issue by Ryguy0777** [HBroHei/NSMRWii#20]
was trying to redirect someone who needed help to your server but the invite is dead, make sure you set the invite to never expire.

**Comment by NKilr** [comment]
![Capture d’écran 2024-12-21 200701](https://github.com/user-attachments/assets/eea3037f-930e-428b-9944-d0ace0baad8f)

it says ( in french ) we invittation expired yup

**Comment by HBroHei** [comment]
Please try the following link: https://discord.gg/z848AykwDr

Thabk you for informing me about that!
